In [3]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0


In [1]:
import torch

In [2]:
t = torch.rand(2, 3)
t_gpu = t.to(torch.device('cuda'))
t_cpu = t_gpu.to(torch.device('cpu'))
print(t_cpu)

tensor([[0.4385, 0.3538, 0.7100],
        [0.5870, 0.8004, 0.3842]])


In [3]:
t = torch.ones(3, 2)
t = t.to('cuda')
print(t)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')


In [4]:
t = torch.rand(2, 3)
t_ones = torch.ones_like(t)
t_zeros = torch.zeros_like(t)
print(t_ones)
print(t_zeros)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [1]:
# 파이토치는 쿠다의 버전에 따라서 호환 가능한 버전을 설치해야 한다.
# 여기서는 쿠다의 버전이 11.4이기에
# 쿠다 11.3과 호환되는 버전을 설치해 보았다.
# CUDA 11.3
# conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch

In [2]:
import torch

In [3]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [4]:
print(m1 + 3)

tensor([[6., 6.]])


In [6]:
# just like NumPy, PyTorch also supports broadcast operation
print(m1 + torch.FloatTensor([[1], [2]]))

tensor([[4., 4.],
        [5., 5.]])


In [8]:
torch.mm(m1, m2.T)

tensor([[12.]])

In [9]:
m1 @ m2.T

tensor([[12.]])

In [10]:
m1.mean()

tensor(3.)

In [11]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean(dim=0))
print(t.mean(dim=1))

tensor([2., 3.])
tensor([1.5000, 3.5000])


In [12]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [13]:
print(t.max())
print(t.max(dim=0))
print(t.max(dim=1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [14]:
t = torch.randn(2, 2, 3)
print(t)

tensor([[[-0.2228,  0.7517, -0.5935],
         [-1.2794,  0.9997,  0.1761]],

        [[-1.0270, -0.4042, -1.0399],
         [ 0.2856, -0.8945, -1.5606]]])


In [15]:
t.shape

torch.Size([2, 2, 3])

In [16]:
t.reshape((4, 3))

tensor([[-0.2228,  0.7517, -0.5935],
        [-1.2794,  0.9997,  0.1761],
        [-1.0270, -0.4042, -1.0399],
        [ 0.2856, -0.8945, -1.5606]])

In [17]:
t.reshape((1,1,4,3))

tensor([[[[-0.2228,  0.7517, -0.5935],
          [-1.2794,  0.9997,  0.1761],
          [-1.0270, -0.4042, -1.0399],
          [ 0.2856, -0.8945, -1.5606]]]])

In [18]:
t.reshape(6,2)

tensor([[-0.2228,  0.7517],
        [-0.5935, -1.2794],
        [ 0.9997,  0.1761],
        [-1.0270, -0.4042],
        [-1.0399,  0.2856],
        [-0.8945, -1.5606]])

In [19]:
t.view(3,4)

tensor([[-0.2228,  0.7517, -0.5935, -1.2794],
        [ 0.9997,  0.1761, -1.0270, -0.4042],
        [-1.0399,  0.2856, -0.8945, -1.5606]])

In [20]:
t.transpose(0, 2)

tensor([[[-0.2228, -1.0270],
         [-1.2794,  0.2856]],

        [[ 0.7517, -0.4042],
         [ 0.9997, -0.8945]],

        [[-0.5935, -1.0399],
         [ 0.1761, -1.5606]]])

In [21]:
t.permute(2, 0, 1)

tensor([[[-0.2228, -1.2794],
         [-1.0270,  0.2856]],

        [[ 0.7517,  0.9997],
         [-0.4042, -0.8945]],

        [[-0.5935,  0.1761],
         [-1.0399, -1.5606]]])

In [22]:
t.unsqueeze(1)

tensor([[[[-0.2228,  0.7517, -0.5935],
          [-1.2794,  0.9997,  0.1761]]],


        [[[-1.0270, -0.4042, -1.0399],
          [ 0.2856, -0.8945, -1.5606]]]])

In [23]:
tmp = t.unsqueeze(-1)

In [24]:
tmp.shape

torch.Size([2, 2, 3, 1])

In [25]:
tmp = tmp.squeeze()

In [26]:
tmp.shape

torch.Size([2, 2, 3])

In [1]:
print('hello')

hello
