In [1]:
import torch

\begin{align}
h_\theta(x) &= wx + b \\
parameter \, \theta &= (w, b) \\
\underset{w, b}{arg\,min} \, J(w, b) &= \frac{1}{m} \sum_{i=1}^{m} \left( h_\theta(x_i) - y_i \right)^2
\end{align}

In [2]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 2*y + 5
z.backward()
print(f'derivative with respect to w: {w.grad}')

derivative with respect to w: 8.0


In [3]:
w = torch.tensor(2.0, requires_grad=True)
nb_epochs = 20
for epoch in range(nb_epochs):
  z = 2*w
  z.backward()
  print(f'derivative with respect to w: {w.grad}')

derivative with respect to w: 2.0
derivative with respect to w: 4.0
derivative with respect to w: 6.0
derivative with respect to w: 8.0
derivative with respect to w: 10.0
derivative with respect to w: 12.0
derivative with respect to w: 14.0
derivative with respect to w: 16.0
derivative with respect to w: 18.0
derivative with respect to w: 20.0
derivative with respect to w: 22.0
derivative with respect to w: 24.0
derivative with respect to w: 26.0
derivative with respect to w: 28.0
derivative with respect to w: 30.0
derivative with respect to w: 32.0
derivative with respect to w: 34.0
derivative with respect to w: 36.0
derivative with respect to w: 38.0
derivative with respect to w: 40.0


In [4]:
w = torch.tensor(2.0, requires_grad=True)
nb_epochs = 20
for epoch in range(nb_epochs):
  z = 2*w
  if w.grad is not None:
    w.grad.zero_()
  z.backward()
  print(f'derivative with respect to w: {w.grad}')

derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0
derivative with respect to w: 2.0


# linear regression

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [7]:
x_train = torch.FloatTensor([[1.0], [2.0], [3.0]])
y_train = torch.FloatTensor([[2.0], [4.0], [6.0]])

In [8]:
model = nn.Linear(1, 1)

In [9]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [10]:
nb_epochs = 2000

In [12]:
for epoch in range(nb_epochs + 1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(f'epoch: {epoch}, cost: {cost.item()}')

epoch: 0, cost: 10.10369873046875
epoch: 100, cost: 0.12628014385700226
epoch: 200, cost: 0.07803339511156082
epoch: 300, cost: 0.04821990057826042
epoch: 400, cost: 0.02979692816734314
epoch: 500, cost: 0.018412666395306587
epoch: 600, cost: 0.011377942748367786
epoch: 700, cost: 0.007030864711850882
epoch: 800, cost: 0.004344642627984285
epoch: 900, cost: 0.0026847373228520155
epoch: 1000, cost: 0.0016590108862146735
epoch: 1100, cost: 0.00102515600156039
epoch: 1200, cost: 0.0006334870122373104
epoch: 1300, cost: 0.00039145664777606726
epoch: 1400, cost: 0.00024189714167732745
epoch: 1500, cost: 0.00014947621093597263
epoch: 1600, cost: 9.236818732460961e-05
epoch: 1700, cost: 5.707731543225236e-05
epoch: 1800, cost: 3.526912769302726e-05
epoch: 1900, cost: 2.1794496205984615e-05
epoch: 2000, cost: 1.346723274764372e-05


In [14]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[1.9957]], requires_grad=True)
Parameter containing:
tensor([0.0097], requires_grad=True)


In [15]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print(pred_y)

tensor([[7.9927]], grad_fn=<AddmmBackward0>)


# data loader

In [16]:
x_train = torch.FloatTensor([
  [73, 80, 75],
  [93, 88, 93],
  [89, 91, 90],
  [96, 98, 100],
  [73, 66, 70],
])
y_train = torch.FloatTensor([
  [152], [185], [180], [196], [142]
])

In [18]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [19]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(f'epoch: {epoch}, cost: {cost.item()}')

epoch: 0, cost: 55771.34375
epoch: 100, cost: 1.5699758529663086
epoch: 200, cost: 1.546587586402893
epoch: 300, cost: 1.524176836013794
epoch: 400, cost: 1.5026980638504028
epoch: 500, cost: 1.4820894002914429
epoch: 600, cost: 1.4623559713363647
epoch: 700, cost: 1.4433848857879639
epoch: 800, cost: 1.4252088069915771
epoch: 900, cost: 1.4077284336090088
epoch: 1000, cost: 1.3909380435943604
epoch: 1100, cost: 1.374792456626892
epoch: 1200, cost: 1.3592609167099
epoch: 1300, cost: 1.3443008661270142
epoch: 1400, cost: 1.3298991918563843
epoch: 1500, cost: 1.3160308599472046
epoch: 1600, cost: 1.302654504776001
epoch: 1700, cost: 1.2897627353668213
epoch: 1800, cost: 1.277314305305481
epoch: 1900, cost: 1.2652853727340698
epoch: 2000, cost: 1.2536617517471313


In [20]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print(pred_y)

tensor([[151.1690]], grad_fn=<AddmmBackward0>)


# mini batch

In [21]:
x_train = torch.FloatTensor([
  [73, 80, 75],
  [93, 88, 93],
  [89, 91, 90],
  [96, 98, 100],
  [73, 66, 70],
])
y_train = torch.FloatTensor([
  [152], [185], [180], [196], [142]
])

from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [22]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [23]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

  if epoch % 100 == 0:
    print(f'epoch: {epoch}, cost: {cost.item()}')

epoch: 0, cost: 3803.757080078125
epoch: 100, cost: 19.77762794494629
epoch: 200, cost: 10.526923179626465
epoch: 300, cost: 16.52126693725586
epoch: 400, cost: 10.940634727478027
epoch: 500, cost: 0.166804239153862
epoch: 600, cost: 5.324745178222656
epoch: 700, cost: 1.8448731899261475
epoch: 800, cost: 1.0133192539215088
epoch: 900, cost: 3.365233898162842
epoch: 1000, cost: 3.4636335372924805
epoch: 1100, cost: 0.08630520105361938
epoch: 1200, cost: 3.4799530506134033
epoch: 1300, cost: 0.7260425686836243
epoch: 1400, cost: 2.4101786613464355
epoch: 1500, cost: 1.48721182346344
epoch: 1600, cost: 1.4005329608917236
epoch: 1700, cost: 0.2810766398906708
epoch: 1800, cost: 1.058101773262024
epoch: 1900, cost: 0.1541774868965149
epoch: 2000, cost: 0.1393575817346573


In [24]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print(pred_y)

tensor([[152.2437]], grad_fn=<AddmmBackward0>)


# custom data set

In [25]:
class CustomNumbers:
  def __init__(self, num) -> None:
    self.numbers = [n for n in range(1, num)]

  def __getitem__(self, idx):
    return self.numbers[idx]

  def __len__(self) -> int:
    return len(self.numbers)

In [27]:
cn = CustomNumbers(100)
print(cn[5:10])
print(len(cn))

[6, 7, 8, 9, 10]
99


In [29]:
class MyDataset(torch.utils.data.Dataset):
  def __init__(self, x_data, y_data) -> None:
    self.x_data = x_data
    self.y_data = y_data

  def __getitem__(self, idx):
    return self.x_data[idx], self.y_data[idx]

  def __len__(self):
    return len(self.x_data)

In [30]:
x_train = torch.FloatTensor([
  [73, 80, 75],
  [93, 88, 93],
  [89, 91, 90],
  [96, 98, 100],
  [73, 66, 70],
])
y_train = torch.FloatTensor([
  [152], [185], [180], [196], [142]
])

from torch.utils.data import DataLoader

dataset = MyDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [31]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
nb_epochs = 2000
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

  if epoch % 100 == 0:
    print(f'epoch: {epoch}, cost: {cost.item()}')

epoch: 0, cost: 284.10784912109375
epoch: 100, cost: 2.836646318435669
epoch: 200, cost: 2.688246965408325
epoch: 300, cost: 0.46292975544929504
epoch: 400, cost: 1.208670973777771
epoch: 500, cost: 0.6055212616920471
epoch: 600, cost: 0.22235219180583954
epoch: 700, cost: 1.341681957244873
epoch: 800, cost: 0.5962480902671814
epoch: 900, cost: 0.6527138948440552
epoch: 1000, cost: 0.5834510922431946
epoch: 1100, cost: 0.2664044201374054
epoch: 1200, cost: 0.9981088042259216
epoch: 1300, cost: 0.7367954850196838
epoch: 1400, cost: 0.4198184311389923
epoch: 1500, cost: 0.5225408673286438
epoch: 1600, cost: 1.1860970258712769
epoch: 1700, cost: 0.24151310324668884
epoch: 1800, cost: 0.4935053884983063
epoch: 1900, cost: 0.22706818580627441
epoch: 2000, cost: 0.3458666205406189


In [32]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print(pred_y)

tensor([[151.0578]], grad_fn=<AddmmBackward0>)
